### ISSUE TITLE
can not get code to work

### ISSUE THREAD

**Issue by aircooler201** [x-magic/kindle-weather-stand-alone#1]
Hi,

thanks for the code and hope you can help me to get it running on my kindle.

Black Kindle 4, jailbroken with usbnetwork, Kual installed.

When i run code from kual it just freeze on initializing screen.
I have try weather.ssh using putty - it stop few processes and freeze. No errors.

When i  try to run get-weather and update-weather in putty, nothing happen also no errors - it just come back to root /folder/$ within second.

Am i missing something?

Thank you

**Comment by aircooler201** [comment]
After removing below from get-weather.sh all seems to work as expected. As i am beginner i am not sure what this line do. Should i expect any issues without it? 
 
Quit when detect a disable flag
if [ -e disable ]; then exit 0; fi

**Comment by x-magic** [comment]
That line is a kill switch. I put it there in case I want to disable the script. If a file named disable presents, the script will quit immediately. 

As of freeze, I believe the script usually takes quite long to boot up actually. On my silver K4NT it took at least 30s. Or another reason could be related to Weather Underground's API change. 

Well my Kindle was in storage for quite a while and currently I can't even got the code to work (bitrotted maybe?) I suppose I should review the codebase and see if I need to update anything.
