### ISSUE TITLE
Weatherunderground API no longer available

### ISSUE THREAD

**Issue by fightforlife** [x-magic/kindle-weather-stand-alone#2]
Just for anyone finding this.

**Comment by x-magic** [comment]
Haven't been in the kitchen for a few day, just realised the issue. 

I currently don't have a timeline on update, but I assume could be done within the month.

**Comment by x-magic** [comment]
I have updated the project to 3.x. Now support Dark Sky API and OpenWeatherMap API. 

This issues is now closed.

**Comment by fightforlife** [comment]
Just wanted to add a big thank you! 
It is working again! 

(I only had to install pytz manually, the scriptwasnt working)
