### ISSUE TITLE
Could not update weather

### ISSUE THREAD

**Issue by aprex83** [x-magic/kindle-weather-stand-alone#3]
Hi, great job for our old k4 !
Perfect installation, files edited as described, but it starts with 'initializing...' and freezes 30s later with 'could not update  weather'. Tried the two weather providers. 

Best regards

**Comment by x-magic** [comment]
That message means the file `/extensions/weather-stand/bin/weather-generator.sh` cannot be executed correctly. 

It could be an error when the python script generates the weather svg file, or it has something to do with the png conversion. My money is on python setup. Have you run prerequisite checker and install necessary components (especially pytz library)? Don't forget there're several API keys need to be filled-in as well. 

As the README.md said, you should test out various scripts via SSH first before running it through KUAL. The initialisation will kill off most of system services to preserve battery life. If you haven't setup WiFi connection correctly, the device will run into infinite loop. If that happens, try to force reboot by press the power button to wake it up, release, and hold down the button for ~15 seconds until you see the Kindle boot screen.

**Comment by aprex83** [comment]
Big thanks for your prompt answer!
Prerequiste checker was ok . I find python for K4 here:
https://www.mobileread.com/forums/showthread.php?t=88004
''Don't forget there're several API keys need to be filled-in as well.'' I just see 1 field in weather-generator-darksky and weather-generator-openweathermaps, right? I tried the complete https address (with my api key, location, etc) in my web browser and it runs fine.
I will try the ssh way and try to see what's wrong with my install.

Thanks a lot, have a good day.

**Comment by x-magic** [comment]
I suggest that you manually run each commands in `weather-generator.sh` and try to identify any error. 

I’ll close this issue for now, if you have further request, please feel free to reopen.

**Comment by aprex83** [comment]
Hi x-magic, 
Foud this:
![Error](https://user-images.githubusercontent.com/50181899/57155130-ec85ca80-6dda-11e9-8d4c-96dacf4dff61.jpg)

Just checked the pytz install in python, numerous folders (as Europe) was missing.
It runs fine now, very great job, thanks again!!!

Best regards

**Comment by x-magic** [comment]
@aprex83 Thanks for showing the error message. I think you are not alone. I guess I need some time to figure out why the prerequisite checker doesn't install pytz correctly. I have opened #4 for this error.
